### PR TITLE
Fix typos in Plugins subdirectory

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell`  
Signed-off-by: luz paz <luzpaz@github.com>

### CODE REVIEW

**Comment by luzpaz** [comment]
Rebased. Anyone care to review ?

**Comment by luzpaz** [comment]
bumping for exposure

**Comment by luzpaz** [comment]
rebased

**Comment by kislinsk** [comment]
Thanks! Merged with a few corrections of wrongly corrected typos.

**Pull request merged**
